apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim  
  labels:
    app: redis-pv-claim
spec:    
  # storageClassName: defaults to Minikube/KIND storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi