apiVersion: v1
kind: Service
metadata:
  name: mailpit-svc
spec:
  type: ClusterIP
  selector:
    app: mailpit-deploy
  ports:
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: smtp-port
    - name: web
      protocol: TCP
      port: 8025
      targetPort: web-port
