apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configs
data:
  PORT: "3000"
  JWT_SESSION_EXP_TIME: "10m"
  JWT_PASSWORD_RECOVERY_EXP_TIME: "10m"
  JWT_EMAIL_VALIDATION_EXP_TIME: "10m"
  JWT_REFRESH_EXP_TIME: "30d"
  MAX_REFRESH_TOKENS_PER_USER: "3"
  MAIL_SERVICE_HOST: "testHost" #TODO: add mailpit
  MAIL_SERVICE_PORT: "5490" #TODO: add mailpit
  MAIL_SERVICE_USER: "testUser" #TODO: add mailpit
  WEB_URL: "http://localhost:3000"
  HTTP_LOGS: "true"
  ADMIN_NAME: "authtaskerAdmin"
  ADMIN_EMAIL: "admin@example.com"
  USERS_API_CACHE_TTL_SECONDS: "10"
  TASKS_API_CACHE_TTL_SECONDS: "10"
  CACHE_HARD_TTL_SECONDS : "30"