namespace: authtasker-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - ../../base/redis
  - ../../base/mongo
  - ../../base/backend

patches:
  - target:
      kind: Deployment
      name: authtasker-deploy
    path: patches/backend-resources.yaml  