# Dev Only and tracked by git intentionally
apiVersion: v1
kind: Secret
metadata:  
  name: backend-secrets  
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-svc:27017/authtasker-dev"
  REDIS_URI: "redis://redis-svc:6379"
  JWT_EMAIL_VALIDATION_PRIVATE_KEY: "emailValidationPrivateKeyDev"
  JWT_PASSWORD_RECOVERY_PRIVATE_KEY: "emailRecoveryPrivateKeyDev"
  JWT_SESSION_PRIVATE_KEY: "sessionPrivateKeyDev"
  JWT_REFRESH_PRIVATE_KEY: "refreshPrivateKeyDev"
  BCRYPT_SALT_ROUNDS: "15"
  PASSWORD_PEPPER: "pepperDevValue"
  MAIL_SERVICE_PASS: "anypassword"
  ADMIN_PASSWORD: "adminpassword"